# Simple Fix Script - Issues 1, 2, 3

param(
    [string]$RootPath = "C:\LMSSystem"
)

Write-Host "=== Applying Fixes ===" -ForegroundColor Green

# Fix 1: Tree Indentation
Write-Host "[1/3] Fixing tree indentation..." -ForegroundColor Yellow
Set-Location "$RootPath\LMSUI\src\app\components\sidebar"

$sidebar = Get-Content "sidebar.component.ts" -Raw
$sidebar = $sidebar -replace '\.tree-children \{[^}]*\}', '.tree-children { padding-left: 24px; }'
Set-Content -Path "sidebar.component.ts" -Value $sidebar
Write-Host "  Done" -ForegroundColor Green

# Fix 2 & 3: Viewer Component
Write-Host "[2/3] Updating viewer component..." -ForegroundColor Yellow
Set-Location "$RootPath\LMSUI\src\app\components\viewer"

# Create the new viewer file
$viewerPath = "viewer.component.ts"
Remove-Item $viewerPath -Force -ErrorAction SilentlyContinue

# Write in chunks to avoid PowerShell string issues
Add-Content $viewerPath "import { ChangeDetectorRef, Component, Input, OnChanges, SimpleChanges } from '@angular/core';"
Add-Content $viewerPath "import { CommonModule } from '@angular/common';"
Add-Content $viewerPath "import { DomSanitizer, SafeResourceUrl } from '@angular/platform-browser';"
Add-Content $viewerPath "import { MatIconModule } from '@angular/material/icon';"
Add-Content $viewerPath "import { MatButtonModule } from '@angular/material/button';"
Add-Content $viewerPath "import { CourseItem } from '../../models/course.model';"
Add-Content $viewerPath "import { CourseService } from '../../services/course.service';"
Add-Content $viewerPath ""
Add-Content $viewerPath "@Component({"
Add-Content $viewerPath "  selector: 'app-viewer',"
Add-Content $viewerPath "  standalone: true,"
Add-Content $viewerPath "  imports: [CommonModule, MatIconModule, MatButtonModule],"
Add-Content $viewerPath "  template: \`"
Add-Content $viewerPath "    <div class=`"viewer`">"
Add-Content $viewerPath "      @if (!selectedItem) {"
Add-Content $viewerPath "        <div class=`"placeholder`">"
Add-Content $viewerPath "          <mat-icon>description</mat-icon>"
Add-Content $viewerPath "          <p>Select a file to view</p>"
Add-Content $viewerPath "        </div>"
Add-Content $viewerPath "      }"
Add-Content $viewerPath "      @if (selectedItem) {"
Add-Content $viewerPath "        <div class=`"content`">"
Add-Content $viewerPath "          <div class=`"file-header`">"
Add-Content $viewerPath "            <h2>{{ selectedItem.name }}</h2>"
Add-Content $viewerPath "          </div>"
Add-Content $viewerPath "          @if (selectedItem.type === 'video') {"
Add-Content $viewerPath "            <div class=`"media-container`">"
Add-Content $viewerPath "              <video controls [src]=`"fileUrl`" class=`"video-player`" [key]=`"selectedItem.id`"></video>"
Add-Content $viewerPath "            </div>"
Add-Content $viewerPath "          }"
Add-Content $viewerPath "          @if (selectedItem.type === 'audio') {"
Add-Content $viewerPath "            <div class=`"audio-container`">"
Add-Content $viewerPath "              <audio controls [src]=`"fileUrl`" class=`"audio-player`" [key]=`"selectedItem.id`"></audio>"
Add-Content $viewerPath "            </div>"
Add-Content $viewerPath "          }"
Add-Content $viewerPath "          @if (selectedItem.type === 'document' && selectedItem.extension === '.pdf') {"
Add-Content $viewerPath "            <iframe [src]=`"sanitizeUrl(fileUrl)`" class=`"document-viewer`" [key]=`"selectedItem.id`"></iframe>"
Add-Content $viewerPath "          }"
Add-Content $viewerPath "          @if (selectedItem.type === 'document' && selectedItem.extension === '.txt') {"
Add-Content $viewerPath "            <div class=`"text-viewer`"><pre class=`"text-content`">{{ textContent }}</pre></div>"
Add-Content $viewerPath "          }"
Add-Content $viewerPath "          @if (selectedItem.type !== 'video' && selectedItem.type !== 'audio' && (selectedItem.type !== 'document' || !['.pdf', '.txt'].includes(selectedItem.extension))) {"
Add-Content $viewerPath "            <div class=`"file-info`">"
Add-Content $viewerPath "              <mat-icon class=`"large-icon`">insert_drive_file</mat-icon>"
Add-Content $viewerPath "              <p>{{ selectedItem.name }}</p>"
Add-Content $viewerPath "              <p>Size: {{ formatSize(selectedItem.size) }}</p>"
Add-Content $viewerPath "              <a [href]=`"fileUrl`" download mat-raised-button color=`"primary`">"
Add-Content $viewerPath "                <mat-icon>download</mat-icon> Download"
Add-Content $viewerPath "              </a>"
Add-Content $viewerPath "            </div>"
Add-Content $viewerPath "          }"
Add-Content $viewerPath "        </div>"
Add-Content $viewerPath "      }"
Add-Content $viewerPath "    </div>"
Add-Content $viewerPath "  \`,"
Add-Content $viewerPath "  styles: [\`"
Add-Content $viewerPath "    .viewer { flex: 1; display: flex; flex-direction: column; height: 100%; overflow: hidden; background: white; }"
Add-Content $viewerPath "    .placeholder { display: flex; flex-direction: column; align-items: center; justify-content: center; height: 100%; color: #999; }"
Add-Content $viewerPath "    .placeholder mat-icon { font-size: 64px; width: 64px; height: 64px; margin-bottom: 16px; }"
Add-Content $viewerPath "    .content { flex: 1; display: flex; flex-direction: column; height: 100%; overflow: hidden; }"
Add-Content $viewerPath "    .file-header { padding: 16px 24px; border-bottom: 1px solid #e0e0e0; flex-shrink: 0; }"
Add-Content $viewerPath "    .file-header h2 { margin: 0; font-size: 18px; }"
Add-Content $viewerPath "    .media-container { flex: 1; display: flex; align-items: center; justify-content: center; background: #000; }"
Add-Content $viewerPath "    .video-player { width: 100%; height: 100%; object-fit: contain; }"
Add-Content $viewerPath "    .audio-container { flex: 1; display: flex; align-items: center; justify-content: center; padding: 48px; }"
Add-Content $viewerPath "    .audio-player { width: 100%; max-width: 600px; }"
Add-Content $viewerPath "    .document-viewer { flex: 1; width: 100%; height: 100%; border: none; }"
Add-Content $viewerPath "    .text-viewer { flex: 1; overflow: auto; background: #fafafa; padding: 24px; }"
Add-Content $viewerPath "    .text-content { font-family: monospace; font-size: 14px; white-space: pre-wrap; margin: 0; background: white; padding: 16px; border-radius: 4px; }"
Add-Content $viewerPath "    .file-info { flex: 1; display: flex; flex-direction: column; align-items: center; justify-content: center; padding: 48px; text-align: center; }"
Add-Content $viewerPath "    .large-icon { font-size: 96px; width: 96px; height: 96px; margin-bottom: 24px; color: #757575; }"
Add-Content $viewerPath "  \`]"
Add-Content $viewerPath "})"
Add-Content $viewerPath "export class ViewerComponent implements OnChanges {"
Add-Content $viewerPath "  @Input() selectedItem: CourseItem | null = null;"
Add-Content $viewerPath "  fileUrl: string = '';"
Add-Content $viewerPath "  textContent: string = '';"
Add-Content $viewerPath "  private previousItemId: number | null = null;"
Add-Content $viewerPath ""
Add-Content $viewerPath "  constructor(private courseService: CourseService, private sanitizer: DomSanitizer, private cdr: ChangeDetectorRef) {}"
Add-Content $viewerPath ""
Add-Content $viewerPath "  ngOnChanges(changes: SimpleChanges) {"
Add-Content $viewerPath "    if (changes['selectedItem'] && this.selectedItem) {"
Add-Content $viewerPath "      if (this.previousItemId !== this.selectedItem.id) {"
Add-Content $viewerPath "        this.previousItemId = this.selectedItem.id;"
Add-Content $viewerPath "        this.textContent = '';"
Add-Content $viewerPath "        this.fileUrl = '';"
Add-Content $viewerPath "        this.cdr.detectChanges();"
Add-Content $viewerPath "        this.loadContent();"
Add-Content $viewerPath "      }"
Add-Content $viewerPath "    }"
Add-Content $viewerPath "  }"
Add-Content $viewerPath ""
Add-Content $viewerPath "  private loadContent() {"
Add-Content $viewerPath "    if (!this.selectedItem) return;"
Add-Content $viewerPath "    this.fileUrl = this.courseService.getFileUrl(this.selectedItem.path);"
Add-Content $viewerPath "    if (this.selectedItem.extension === '.txt') {"
Add-Content $viewerPath "      fetch(this.fileUrl).then(res => res.text()).then(text => {"
Add-Content $viewerPath "        this.textContent = text;"
Add-Content $viewerPath "        this.cdr.detectChanges();"
Add-Content $viewerPath "      }).catch(err => console.error('Failed to load text', err));"
Add-Content $viewerPath "    }"
Add-Content $viewerPath "  }"
Add-Content $viewerPath ""
Add-Content $viewerPath "  sanitizeUrl(url: string): SafeResourceUrl {"
Add-Content $viewerPath "    return this.sanitizer.bypassSecurityTrustResourceUrl(url);"
Add-Content $viewerPath "  }"
Add-Content $viewerPath ""
Add-Content $viewerPath "  formatSize(bytes: number): string {"
Add-Content $viewerPath "    if (bytes < 1024) return bytes + ' B';"
Add-Content $viewerPath "    if (bytes < 1048576) return (bytes / 1024).toFixed(2) + ' KB';"
Add-Content $viewerPath "    if (bytes < 1073741824) return (bytes / 1048576).toFixed(2) + ' MB';"
Add-Content $viewerPath "    return (bytes / 1073741824).toFixed(2) + ' GB';"
Add-Content $viewerPath "  }"
Add-Content $viewerPath "}"

Write-Host "  Done" -ForegroundColor Green

Write-Host "[3/3] Complete!" -ForegroundColor Yellow
Write-Host ""
Write-Host "=== All Fixes Applied ===" -ForegroundColor Green
Write-Host "Fixed:"
Write-Host "  - Tree indentation (24px per level)"
Write-Host "  - Video fills entire panel"
Write-Host "  - File switching works properly"
Write-Host ""
Write-Host "Restart Angular: cd LMSUI && ng serve" -ForegroundColor Cyan
Write-Host ""